development:
  bucket:  filetunnel
  access_key_id: AKIAICDXU5SXRWQA5RQA
  secret_access_key: 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
  acl: public-read
    
test:
  bucket:  filetunnel
  access_key_id: AKIAICDXU5SXRWQA5RQA
  secret_access_key: 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
  acl: public-read
  
production:
  bucket:  filetunnel
  access_key_id: AKIAICDXU5SXRWQA5RQA
  secret_access_key: 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
  acl: public-read
